project_id = "ehzikjukkowxvfkfiyxu"

[functions.send-approval-email]
verify_jwt = false

[functions.generate-sql]
verify_jwt = false

[functions.powerbi-token]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.encrypt-connection]
verify_jwt = false

[functions.execute-sql]
verify_jwt = false
